"""Class Table

Revision ID: abf37bc2083e
Revises: 415d61526280
Create Date: 2025-04-10 23:49:56.028735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf37bc2083e'
down_revision: Union[str, None] = '415d61526280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('students_count', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('school_year', sa.String(), nullable=False),
    sa.Column('class_leader_id', sa.Integer(), nullable=True),
    sa.Column('class_photo_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('class_room_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('students', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'class', ['class_id'], ['id'])
    op.add_column('teachers', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_url')
    op.drop_column('teachers', 'gender')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'class_id')
    op.drop_table('class')
    # ### end Alembic commands ###
