"""Some changes

Revision ID: d9df474f016f
Revises: abf37bc2083e
Create Date: 2025-04-21 18:45:53.080613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9df474f016f'
down_revision: Union[str, None] = 'abf37bc2083e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('teacher_username', sa.String(), nullable=True))
    op.add_column('class', sa.Column('class_leader_username', sa.String(), nullable=True))
    op.drop_constraint('class_teacher_id_fkey', 'class', type_='foreignkey')
    op.create_foreign_key(None, 'class', 'teachers', ['teacher_username'], ['username'])
    op.drop_column('class', 'class_leader_id')
    op.drop_column('class', 'teacher_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('class', sa.Column('class_leader_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'class', type_='foreignkey')
    op.create_foreign_key('class_teacher_id_fkey', 'class', 'teachers', ['teacher_id'], ['id'])
    op.drop_column('class', 'class_leader_username')
    op.drop_column('class', 'teacher_username')
    # ### end Alembic commands ###
